fragment ArticlesParts on Articles {
  __typename
  title
  date
  slug
  excerpt
  featureImage
  body
}

fragment CaseStudiesParts on CaseStudies {
  __typename
  title
  date
  slug
  excerpt
  featureImage
  body
}
